CREATE TABLE IF NOT EXISTS Options(
	name VARCHAR PRIMARY KEY NOT NULL,
	val NOT NULL
);

CREATE TABLE IF NOT EXISTS Users(
	userId INTEGER PRIMARY KEY NOT NULL,
	userName VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Cookie(
	name VARCHAR PRIMARY KEY NOT NULL,
	content VARCHAR NOT NULL,
	lifetime INTEGER NOT NULL
);
