CREATE TABLE IF NOT EXISTS ShatteredPlans_Achievements(
	userId INTEGER PRIMARY KEY NOT NULL REFERENCES Users(userId) ON DELETE CASCADE,
	achievements BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS ShatteredPlans_Profile(
	userId INTEGER PRIMARY KEY NOT NULL REFERENCES Users(userId) ON DELETE CASCADE,
	profile BLOB NOT NULL
);
